#!/bin/bash
#
# This script prints your job history using sacct. One can specify the
# number of days to go back in time and whether or not to show the
# individual job steps.
#
# Example usage:
#
#   $ myjobs
#   $ myjobs -d 14
#   $ myjobs -d 2 -a
#   $ myjobs --days 10 --all

print_help() {
  echo -e "\nNAME"
  echo -e "\tmyjobs - show Slurm job history\n"
  echo -e "USAGE"
  echo -e "\tmyjobs [-d days | -a] [-h]\n"
  echo -e "OPTIONS"
  echo -e "\t-a,--all"
  echo -e "\t\tShow all intermediate job steps"
  echo -e "\t-d,--days"
  echo -e "\t\tShow jobs over this many previous days from now (default: 7)"
}

# defaults
days=7
show_all_steps=false

# parse command-line arguments
while [[ "$#" -gt 0 ]]
do
  case $1 in
    -h|--help)
      print_help
      exit
      ;;
    -d|--days)
      days="$2";
      shift;
      ;;
    -a|--all)
      show_all_steps=true;
      ;;
  esac
  shift
done

startdate=$(date -d"${days} days ago" +%D);
FMT=jobid%12,state,start,elapsed,timelimit,ncpus%5,nnodes%6,reqmem%10,alloctres%50,partition,jobname%8;
if $show_all_steps; then
    sacct -u $USER -S $startdate -o $FMT;
else
    sacct -u $USER -S $startdate -o $FMT -X;
fi
